#Base image is in https://registry.hub.docker.com/_/golang/
FROM arm32v7/golang:latest

WORKDIR /tmp

# MAINTAINER Dawid dkadds2@gmail.com

# Install beego & bee
RUN go get github.com/astaxie/beego
RUN go get github.com/beego/bee
RUN go get gopkg.in/mgo.v2/bson
RUN go get github.com/dgrijalva/jwt-go
RUN go get github.com/garyburd/redigo/redis
# ADD . /go/src/

WORKDIR /
